
package GUI;


public class SzamlaDialog extends javax.swing.JDialog {

    
    public SzamlaDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSzamla = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        btnTorol = new javax.swing.JButton();
        lbUj = new java.awt.Label();
        lbModosit1 = new java.awt.Label();
        lbTorol = new java.awt.Label();
        btnTorol1 = new javax.swing.JButton();
        lbMegrendeles = new java.awt.Label();
        btnModosit = new javax.swing.JButton();
        lbDatumKeres1 = new java.awt.Label();
        btnDatumKeres = new javax.swing.JButton();
        btnUjDolgozo2 = new javax.swing.JButton();
        btnCSVExport1 = new javax.swing.JButton();
        lbDatumKeres2 = new java.awt.Label();
        choiceRendez = new java.awt.Choice();
        tfKereses = new javax.swing.JTextField();
        btnKeres = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableSzamla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableSzamla.setAutoscrolls(false);
        jTableSzamla.getTableHeader().setReorderingAllowed(false);
        jTableSzamla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSzamlaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSzamla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 1092, 366));

        buttonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTorol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/delete.png"))); // NOI18N
        btnTorol.setEnabled(false);
        btnTorol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTorolActionPerformed(evt);
            }
        });
        buttonPanel.add(btnTorol, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 80, 80));

        lbUj.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbUj.setText("Módosít");
        buttonPanel.add(lbUj, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, 38));

        lbModosit1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbModosit1.setText("Hozzáad");
        buttonPanel.add(lbModosit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 38));

        lbTorol.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbTorol.setText("Töröl");
        buttonPanel.add(lbTorol, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, 38));

        btnTorol1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/icons8-purchase-order-64.png"))); // NOI18N
        btnTorol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTorol1ActionPerformed(evt);
            }
        });
        buttonPanel.add(btnTorol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 80, 80));

        lbMegrendeles.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbMegrendeles.setText("Áru történet");
        buttonPanel.add(lbMegrendeles, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, 38));

        btnModosit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/wrench.png"))); // NOI18N
        btnModosit.setPreferredSize(new java.awt.Dimension(60, 60));
        btnModosit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModositActionPerformed(evt);
            }
        });
        buttonPanel.add(btnModosit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 80, 80));

        lbDatumKeres1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbDatumKeres1.setText("Datum szerinti szűrés");
        buttonPanel.add(lbDatumKeres1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, -1, 38));

        btnDatumKeres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/calendar.png"))); // NOI18N
        btnDatumKeres.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDatumKeres.setBorderPainted(false);
        btnDatumKeres.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDatumKeres.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnDatumKeres.setFocusable(false);
        btnDatumKeres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatumKeresActionPerformed(evt);
            }
        });
        buttonPanel.add(btnDatumKeres, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 80, 80));

        btnUjDolgozo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/add.png"))); // NOI18N
        btnUjDolgozo2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUjDolgozo2.setBorderPainted(false);
        btnUjDolgozo2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUjDolgozo2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnUjDolgozo2.setFocusable(false);
        btnUjDolgozo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUjDolgozo2ActionPerformed(evt);
            }
        });
        buttonPanel.add(btnUjDolgozo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 80, 80));

        btnCSVExport1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/csv.png"))); // NOI18N
        btnCSVExport1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCSVExport1.setBorderPainted(false);
        btnCSVExport1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCSVExport1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnCSVExport1.setFocusable(false);
        btnCSVExport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCSVExport1ActionPerformed(evt);
            }
        });
        buttonPanel.add(btnCSVExport1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 80, 80));

        lbDatumKeres2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbDatumKeres2.setText("CSV \nexport");
        buttonPanel.add(lbDatumKeres2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 100, 50));

        getContentPane().add(buttonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 25, 920, 270));

        choiceRendez.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        choiceRendez.add("");
        choiceRendez.add("Rendezés név szerint növekvő sorrendben");
        choiceRendez.add("Rendezés név szerint növekvő sorrendben");
        choiceRendez.add("Rendezés megrendelések száma szerint növekvő sorrendben");
        choiceRendez.add("Rendezés megrendelések száma szerint csökkenő sorrendben");
        choiceRendez.select(0);
        getContentPane().add(choiceRendez, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 86, 323, 48));

        tfKereses.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfKeresesKeyReleased(evt);
            }
        });
        getContentPane().add(tfKereses, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 350, 179, 39));

        btnKeres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/icons8-suche-25.png"))); // NOI18N
        btnKeres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeresActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeres, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 350, 40, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableSzamlaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSzamlaMouseClicked

    }//GEN-LAST:event_jTableSzamlaMouseClicked

    private void btnTorolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTorolActionPerformed
        //        int selectedRow = jTableDolgozo.getSelectedRow();
        //
        //        if (selectedRow > -1) {
            //            int selectedId = (Integer) tableModel.getValueAt(jTableDolgozo.getSelectedRow(), 0);
            //
            //            try {
                //                dolgozoJDBC.delete(selectedId);
                //                DolgozoJTable.delete(selectedRow, tableModel);
                //            } catch (SQLException ex) {
                //                JOptionPane.showMessageDialog(null, ex.getMessage(), "Hiba", JOptionPane.ERROR_MESSAGE);
                //            }
            //        }
    }//GEN-LAST:event_btnTorolActionPerformed

    private void btnTorol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTorol1ActionPerformed
        
    }//GEN-LAST:event_btnTorol1ActionPerformed

    private void btnModositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModositActionPerformed
        //        int selectedRow = jTableDolgozo.getSelectedRow();
        //
        //        if (selectedRow > -1) {
            //
            //            int selectedId = (int) tableModel.getValueAt(jTableDolgozo.getSelectedRow(), 0);
            //
            //            JModositDolgozoDialog dialog;
            //
            //            try {
                //
                //                dolgozo = dolgozoJDBC.findById(selectedId);
                //                int id = dolgozo.getId();
                //
                //                dialog = new JModositDolgozoDialog(null, true, dolgozo);
                //                dialog.setTitle("Dolgozó adatainak módoítása");
                //                dialog.setVisible(true);
                //
                //                if (dialog.isOk()) {
                    //                    dolgozo = dialog.getDolgozo();
                    //                    dolgozoJDBC.update(dolgozo, id);
                    //                    DolgozoJTable.updateRecord(selectedRow, dolgozo, tableModel);
                    //                }
                //
                //            } catch (SQLException ex) {
                //                Logger.getLogger(JDolgozoDialog.class.getName()).log(Level.SEVERE, null, ex);
                //            }
            //        }
    }//GEN-LAST:event_btnModositActionPerformed

    private void btnDatumKeresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatumKeresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDatumKeresActionPerformed

    private void btnUjDolgozo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUjDolgozo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUjDolgozo2ActionPerformed

    private void btnCSVExport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCSVExport1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCSVExport1ActionPerformed

    private void tfKeresesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfKeresesKeyReleased
        if(tfKereses.getText().equals("")){

            //            try {
                //                this.tableModel=DolgozoJTable.createTable(columnLabel,dolgozoJDBC.findAll());
                //            } catch (SQLException ex) {
                //                Logger.getLogger(JDolgozoDialog.class.getName()).log(Level.SEVERE, null, ex);
                //            }
            //
            //            jTableDolgozo.setModel(tableModel);
            //            DolgozoJTable.setInvisible(0, jTableDolgozo);

        }
    }//GEN-LAST:event_tfKeresesKeyReleased

    private void btnKeresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeresActionPerformed

        //        Filter filter=new Filter(tfKereses.getText());
        //
        //        try {
            //
            //            this.dolgozoJDBC = new DolgozoRepositoryJDBC();
            //            this.tableModel = DolgozoJTable.createTable(columnLabel, filter.findByRegEx(dolgozoJDBC.findAll()));
            //
            //        } catch (SQLException ex) {
            //
            //        }
        //
        //        jTableDolgozo.setModel(tableModel);
        //        DolgozoJTable.setInvisible(0, jTableDolgozo);
    }//GEN-LAST:event_btnKeresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SzamlaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SzamlaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SzamlaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SzamlaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SzamlaDialog dialog = new SzamlaDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCSVExport1;
    private javax.swing.JButton btnDatumKeres;
    private javax.swing.JButton btnKeres;
    private javax.swing.JButton btnModosit;
    private javax.swing.JButton btnTorol;
    private javax.swing.JButton btnTorol1;
    private javax.swing.JButton btnUjDolgozo2;
    private javax.swing.JPanel buttonPanel;
    private java.awt.Choice choiceRendez;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSzamla;
    private java.awt.Label lbDatumKeres1;
    private java.awt.Label lbDatumKeres2;
    private java.awt.Label lbMegrendeles;
    private java.awt.Label lbModosit1;
    private java.awt.Label lbTorol;
    private java.awt.Label lbUj;
    private javax.swing.JTextField tfKereses;
    // End of variables declaration//GEN-END:variables
}
